### ISSUE TITLE
Fix remaining camera positions

### ISSUE THREAD

**Issue by bozoweed** [StockholmCityRP/esx_tattooshop#1]
You have made a really good jobs but can you please fix the camera ?

**Comment by HawaiiBeach** [comment]
8153d8f42a6949c2a553df3a2b24f8fb6d8c470f

**Comment by HawaiiBeach** [comment]
Re opening as not all tattoos have been completed

**Comment by HawaiiBeach** [comment]
Never mind I forgot to fetch the latest stuff

**Comment by Mew2cry** [comment]
some tattoo are on the butt / hips so it is possible not to see them
