### ISSUE TITLE
 cant save the tattoos

### ISSUE THREAD

**Issue by samabergh** [StockholmCityRP/esx_tattooshop#2]
hi when i buys the tattoos they dont save. but it works fine and it is werry nice.
Hope i can get some help. and yeah i have all i need to get it work :p i have a rp server and this is the only script i have problems with now but i cant figure out whats wrong.

**Comment by HawaiiBeach** [comment]
Investigating...

**Comment by Mew2cry** [comment]
not fixed, just got that issue after updating the script :)

**Comment by samabergh** [comment]
dont save now either, maby it is something i can do at my end. they work great until i log in and out.
But great job with the script, now you see all the tattoos and it is many of them.
